name: Create Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export game to Github
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Create Game Release
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.5.3/Godot_v3.5.3-stable_linux_headless.64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.5.3/Godot_v3.5.3-stable_export_templates.tpz
          relative_project_path: ./Godot
          use_godot_3: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_CREDENTIALS }}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
