name: Deploy to Itch.IO

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release_html:
    runs-on: ubuntu-latest
    steps:
      - name: Download HTML5
        id: download-html
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: "latest"
          file: pirate-bomb.zip
          token: "${{ secrets.GH_CREDENTIALS }}"

      - name: Deploy to Itch.IO (HTML5)
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html
          ITCH_GAME: pirate-bomb
          ITCH_USER: Josephblt
          PACKAGE: pirate-bomb.zip